[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "asf_kerchunk_timeseries"
authors = [
    {name = "Alaska Satellite Facility Discovery Team", email = "uaf-asf-discovery@alaska.edu"},
]
description = """This package is a wrapper around [Kerchunk](https://github.com/fsspec/kerchunk) for generating 
zarr stores for individual netcdf4/hdf5 files as well as consolidating spatially aligned zarr stores 
into a single temporal zarr store, indexed by the source_file_name."""

readme = "README.MD"
requires-python = ">=3.9"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "aiobotocore==2.15.1",
    "kerchunk==0.2.6",
    "s3fs==2024.9.0",
    "ujson==5.10.0",
    "zarr==2.18.3",
    "h5py==3.12.1",
]

[project.optional-dependencies]
dev = [
    "pytest==8.3.3",
]
